[platform]
enabled = false
identifier = "sentinel"
name = "Microsoft Sentinel"
subschema = "Microsoft Sentinel"
description = """Microsoft Sentinel delivers intelligent security analytics
and threat intelligence across the enterprise. With Microsoft Sentinel, you
get a single solution for attack detection, threat visibility, proactive
hunting, and threat response."""
flags = [""]

#[[modifiers]]
#name = "Modifier Demo"
#description = "Example of using modifiers as a development lifecycle automation"
#[modifiers.conditions]
#status = ["DEVELOPMENT"]
#[modifiers.modifications]
#alert.severity = "Informational"
#alert.title = "prefix::Staging "

[[tenants]]
name = "Default"
description = "Tenant Description"
deployment = "ALWAYS" #STAGING, PRODUCTION, MANUAL (only when defined in MDR) or ALWAYS
[tenants.setup]
proxy = true
ssl = true
resource_group = "lzslz_rg"
workspace_name =  "lzslz-workspace8015868214"
workspace_id = "$AZURE_WORKSPACE_ID"
azure_tenant_id = "$AZURE_TENANT_ID"
azure_subscription_id = "$AZURE_SUBSCRIPTION_ID"
azure_client_id = "$AZURE_CLIENT_ID"
azure_client_secret = "$AZURE_CLIENT_SECRET"
