[platform]
enabled = true
identifier = "sentinel"
name = "Microsoft Sentinel"
subschema = "Microsoft Sentinel"
description = """Microsoft Sentinel delivers intelligent security analytics
and threat intelligence across the enterprise. With Microsoft Sentinel, you
get a single solution for attack detection, threat visibility, proactive
hunting, and threat response."""
flags = [""]

#[[modifiers]]
#name = "Modifier Demo"
#description = "Example of using modifiers as a development lifecycle automation"
#[modifiers.conditions]
#status = ["DEVELOPMENT"]
#[modifiers.modifications]
#alert.severity = "Informational"
#alert.title = "prefix::Staging "

[[tenants]]
name = "Placeholder"
description = "Used to generate schema in ShareTide, not used for actual deployments"
deployment = "MANUAL" #STAGING, PRODUCTION, MANUAL (only when defined in MDR) or ALWAYS
[tenants.setup]
proxy = false
ssl = true
resource_group = ""
workspace_name = ""
workspace_id = ""
azure_tenant_id = ""
azure_subscription_id = ""
azure_client_id = ""
azure_client_secret = ""
