[platform]
enabled = false
identifier = "sentinel_one"
name = "Sentinel One"
subschema = "Sentinel One"
description = """STAR Rules Engine is a rules-based engine which enables users
to transform queries of cloud workload telemetry into automated threat hunting
rules. Whenever a match is made, these custom rules trigger alerts and, optionally,
automated response actions.
"""
flags = [""]

#[[modifiers]]
#name = "Modifier Demo"
#description = "Example of using modifiers as a development lifecycle automation"
#[modifiers.conditions]
#status = ["STAGING"]
#[modifiers.modifications]
#alert.severity = "Informational"
#alert.title = "prefix::Staging "

#[[tenants]]
#name = "Environment::Name"
#description = "Description"
#deployment = "ALWAYS" #STAGING, PRODUCTION, MANUAL (only when defined in MDR) or ALWAYS
#[tenants.setup]
#proxy = true
#ssl = true
#url =  #Management URL
#account_id = 
##site_id = "Site name within scope, exactly as console"
#api_token = "$SENTINEL_ONE_API_TOKEN"