name: Addition of credentials to OAuth applications and service principals
criticality: Emergency
references:
  public:
    1: https://msrc-blog.microsoft.com/2020/12/13/customer-guidance-on-recent-nation-state-cyber-attacks/
  #internal:
    #a: 

metadata:
  uuid: a8c7b250-a2d4-4a0d-82f8-23dc99c77d7b
  schema: tvm::2.0
  tlp: clear
  version: 4
  created: 2022-02-21
  modified: 2025-01-01
  organisation:
    uuid: 56b0a0f0-b0bc-47d9-bb46-02f80ae2065a
    name: EC DIGIT CSOC

threat:
  actors:
    - name: att&ck::G0016 #[Enterprise] APT29, Blue Kitsune, Cozy Bear, CozyDuke, Dark Halo, IRON HEMLOCK, IRON RITUAL, Midnight Blizzard, NOBELIUM, NobleBaron, SolarStorm, The Dukes, UNC2452, UNC3524, YTTRIUM
    - name: misp::2ee5ed7a-c4d0-40be-a837-20817474a15b #UNC2452, DarkHalo, StellarParticle, NOBELIUM, Solar Phoenix, Midnight Blizzard
  killchain: Lateral Movement
  att&ck:
    - T1098.001
  terrain: >
    Adversaries need to have gained a sufficient foothold in the  on-premises
    environment before starting to modify Azure  Active Directory.
  domains:
    - Public Cloud
    - Enterprise
  targets:
    - Identity Services
  platforms:
    - Azure AD
  severity: Highly significant incident
  leverage:
    - Dwelling
    - Denial of Service
  impact:
    - Identity Theft
    - Data Breach
    - Impairement
    - IP Loss
  viability: Very Likely
  description: |
    The actor has been observed adding credentials (x509 keys or password
    credentials) to one or more legitimate OAuth Applications or Service
    Principals, usually with existing Mail.Read or Mail.ReadWrite permissions,
    which grants the ability to read mail content from Exchange Online via
    Microsoft Graph or Outlook REST. Examples include mail archiving
    applications. Permissions are usually, but not always, AppOnly.
 
    The actor may use their administrator privileges to grant additional
    permissions to the target Application or Service Principal (e.g.  Mail.Read,
    Mail.ReadWrite).